import { usePage } from '@inertiajs/react';

import type { SharedPageProps } from '@/types/inertia';
import {
  canCreateRoles,
  canCreateCustomers,
  canCreateProducts,
  canDeleteRoles,
  canDeleteCustomers,
  canDeleteProducts,
  canUpdateRoles,
  canUpdateCustomers,
  canUpdateProducts,
  canViewRoles,
  canViewCustomers,
  canViewProducts,
  canViewVendors,
  canCreateVendors,
  canUpdateVendors,
  canDeleteVendors,
  canViewWebsiteOrders,
  canUpdateWebsiteOrders,
  canViewCustomOrders,
  canCreateCustomOrders,
  canUpdateCustomOrders,
  canDeleteCustomOrders,
  canViewCards,
  canCreateCards,
  canUpdateCards,
  canDeleteCards,
  canViewAppointments,
  canCreateAppointments,
  canUpdateAppointments,
  canDeleteAppointments,
  canViewOwnAppointments,
  canCreateOwnAppointments,
  canUpdateOwnAppointments,
  canDeleteOwnAppointments,
  canBookOwnAppointments,
  canViewContacts,
  canViewOwnContacts,
  canCreateContacts,
  canDeleteContacts,
  canCreateOwnContacts,
  canDeleteOwnContacts,
  canViewReviews,
  canViewOwnReviews,
  canCreateReviews,
  canUpdateReviews,
  canDeleteReviews,
  canCreateOwnReviews,
  canUpdateOwnReviews,
  canDeleteOwnReviews,
  DASHBOARD_ACCESS_PERMISSIONS,
  hasAnyPermissionForUser,
  hasPermissionForUser,
  isCustomerRole,
  resolveHomeHref,
} from '@/lib/permissions';

export function useAuth() {
  const { auth } = usePage<{ auth: SharedPageProps['auth'] }>().props;
  const roleNames = auth.user?.roles?.map((role) => role.name);

  return {
    user: auth.user,
    permissions: auth.permissions,
    isAuthenticated: () => auth.user !== null,
    isCustomer: () => isCustomerRole(roleNames),
    hasPermission: (permission: string) =>
      hasPermissionForUser(auth.permissions, permission),
    hasAnyPermission: (permissions: readonly string[]) =>
      hasAnyPermissionForUser(auth.permissions, permissions),
    hasAbility: (permission: string) =>
      hasPermissionForUser(auth.permissions, permission),
    hasAnyAbility: (permissions: readonly string[]) =>
      hasAnyPermissionForUser(auth.permissions, permissions),
    canViewDashboard: () =>
      !isCustomerRole(roleNames) &&
      hasAnyPermissionForUser(auth.permissions, DASHBOARD_ACCESS_PERMISSIONS),
    canViewRoles: () => canViewRoles(auth.permissions),
    canCreateRoles: () => canCreateRoles(auth.permissions),
    canUpdateRoles: () => canUpdateRoles(auth.permissions),
    canDeleteRoles: () => canDeleteRoles(auth.permissions),
    canViewCustomers: () => canViewCustomers(auth.permissions),
    canCreateCustomers: () => canCreateCustomers(auth.permissions),
    canUpdateCustomers: () => canUpdateCustomers(auth.permissions),
    canDeleteCustomers: () => canDeleteCustomers(auth.permissions),
    canViewProducts: () => canViewProducts(auth.permissions),
    canCreateProducts: () => canCreateProducts(auth.permissions),
    canUpdateProducts: () => canUpdateProducts(auth.permissions),
    canDeleteProducts: () => canDeleteProducts(auth.permissions),
    canViewVendors: () => canViewVendors(auth.permissions),
    canCreateVendors: () => canCreateVendors(auth.permissions),
    canUpdateVendors: () => canUpdateVendors(auth.permissions),
    canDeleteVendors: () => canDeleteVendors(auth.permissions),
    canViewWebsiteOrders: () => canViewWebsiteOrders(auth.permissions),
    canUpdateWebsiteOrders: () => canUpdateWebsiteOrders(auth.permissions),
    canViewCustomOrders: () => canViewCustomOrders(auth.permissions),
    canCreateCustomOrders: () => canCreateCustomOrders(auth.permissions),
    canUpdateCustomOrders: () => canUpdateCustomOrders(auth.permissions),
    canDeleteCustomOrders: () => canDeleteCustomOrders(auth.permissions),
    canViewCards: () => canViewCards(auth.permissions),
    canCreateCards: () => canCreateCards(auth.permissions),
    canUpdateCards: () => canUpdateCards(auth.permissions),
    canDeleteCards: () => canDeleteCards(auth.permissions),
    canViewAppointments: () => canViewAppointments(auth.permissions),
    canCreateAppointments: () => canCreateAppointments(auth.permissions),
    canUpdateAppointments: () => canUpdateAppointments(auth.permissions),
    canDeleteAppointments: () => canDeleteAppointments(auth.permissions),
    canViewOwnAppointments: () => canViewOwnAppointments(auth.permissions),
    canCreateOwnAppointments: () => canCreateOwnAppointments(auth.permissions),
    canUpdateOwnAppointments: () => canUpdateOwnAppointments(auth.permissions),
    canDeleteOwnAppointments: () => canDeleteOwnAppointments(auth.permissions),
    canBookOwnAppointments: () => canBookOwnAppointments(auth.permissions),
    canViewContacts: () => canViewContacts(auth.permissions),
    canViewOwnContacts: () => canViewOwnContacts(auth.permissions),
    canCreateContacts: () => canCreateContacts(auth.permissions),
    canDeleteContacts: () => canDeleteContacts(auth.permissions),
    canCreateOwnContacts: () => canCreateOwnContacts(auth.permissions),
    canDeleteOwnContacts: () => canDeleteOwnContacts(auth.permissions),
    canViewReviews: () => canViewReviews(auth.permissions),
    canViewOwnReviews: () => canViewOwnReviews(auth.permissions),
    canCreateReviews: () => canCreateReviews(auth.permissions),
    canUpdateReviews: () => canUpdateReviews(auth.permissions),
    canDeleteReviews: () => canDeleteReviews(auth.permissions),
    canCreateOwnReviews: () => canCreateOwnReviews(auth.permissions),
    canUpdateOwnReviews: () => canUpdateOwnReviews(auth.permissions),
    canDeleteOwnReviews: () => canDeleteOwnReviews(auth.permissions),
    homeHref: resolveHomeHref(
      auth.permissions.map((permission) => permission.name),
      auth.user?.active_template,
      roleNames,
    ),
  };
}
